CREATE DATABASE STAFF_MANAGEMENT_MODULE;

USE STAFF_MANAGEMENT_MODULE;

-- DESIG TABLE
CREATE TABLE DESIG (
    DESIG_ID INT AUTO_INCREMENT PRIMARY KEY,
    DESIG VARCHAR(255) NOT NULL
);

-- STAFF TABLE
CREATE TABLE STAFF (
    STAFF_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    MIDDLE_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    DESIG_ID INT,
    ALTENATE_CONTACT_NO VARCHAR(15),
    PROFILE_PICTURE VARCHAR(255),
    GENDER ENUM('Male', 'Female', 'Other'),
    DATE_OF_BIRTH DATE,
    REPORTING_TO INT,
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    PASSWORD VARCHAR(255),
    CONFIRM_PASSWORD VARCHAR(255),
    FOREIGN KEY (DESIG_ID) REFERENCES DESIG(DESIG_ID)
);

-- STAFF_DETAILS TABLE
CREATE TABLE STAFF_DETAILS (
    STAFF_ID INT,
    STAFF_DETAIL_ID INT,
    COMPANY_NAME VARCHAR(100),
    EXPERIENCE INT,
    DOCUMENT_DETAILS TEXT,
    UPLOAD_DOCS BLOB,
    QUALIFICATION VARCHAR(255),
    DEGREE_CERTIFICATE BLOB,
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)
);

-- Inserting sample data into DESIG TABLE
INSERT INTO DESIG (DESIG) VALUES 
    ('Permanent'), 
    ('Contract'),
    ('Counseller'),
    ('Temporary'),
    ('Freelancer');

-- Inserting sample data into STAFF TABLE
INSERT INTO STAFF (FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, PHONE, DESIG_ID, ALTENATE_CONTACT_NO, PROFILE_PICTURE, GENDER, DATE_OF_BIRTH, REPORTING_TO, STATE, COUNTRY, PASSWORD, CONFIRM_PASSWORD)
VALUES 
    ('John', 'Doe', '', 'john@example.com', '123456789', 1, '987654321', 'profile_pic.jpg', 'Male', '1985-05-10', NULL, 'California', 'USA', 'password123', 'password123'),
    ('Jane', '', 'Smith', 'jane@example.com', '987654321', 2, NULL, 'profile_pic.jpg', 'Female', '1990-03-15', NULL, 'Texas', 'USA', 'password456', 'password456');

-- Inserting sample data into STAFF_DETAILS TABLE
INSERT INTO STAFF_DETAILS (STAFF_ID, EMPLOY_ID, COMPANY_NAME, EXPERIENCE, DOCUMENT_DETAILS, UPLOAD_DOCS, QUALIFICATION, DEGREE_CERTIFICATE)
VALUES 
    (1, 1001, 'ABC Corporation', 5, 'Experience in sales and marketing.', NULL, 'MBA in Marketing', NULL),
    (2, 1002, 'XYZ Company', 3, 'Experience in customer service.', NULL, 'Bachelor of Arts', NULL);
